server:
  environment: dev
  port: 0.0.0.0:8080

mysql:
  dsn: "root:root@tcp(localhost:3307)/mizuflow?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

etcd:
  endpoints:
    - "localhost:2379"
  dial_timeout: 5s

workers:
  outbox_interval: 1s
  reconciler_interval: 1h
  reconciler_batch_size: 100
  reconciler_batch_delay: 50ms

stream:
  heartbeat_interval: 15s
  hub_buffer_size: 4096

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 168h # 7 days

ratelimit:
  requests_per_second: 5
